data_dir: "data"
reads_dir: "processedReads"
analysis_dir: "analysis"

reference: "data/references/hg38.fa"
chromosome_names: "ucsc"

nhmmer: "tools/hmmer/bin/nhmmer"

datasets:
  - _1_pre_TW
  - _2_flight_TW
  - _3_post_TW
  - _1_pre_HR
  - _2_flight_HR
  - _3_post_HR
