data_dir: "data/reference_extended/edgecase"

reference: "data/references/hg38.fa"
telomere_model: "models/M19947.hmm"
chromosome_names: "ucsc"

nhmmer: "tools/hmmer/bin/nhmmer"
densityplot_bin_size: 100
density_window_size: 120

datasets:
  - _1_pre_TW
  - _2_flight_TW
  - _3_post_TW
  - _1_pre_HR
  - _2_flight_HR
  - _3_post_HR

nasa_timepoints:
  - 1_pre
  - 2_flight
  - 3_post

nasa_subjects:
  - TW
  - HR
