data_dir: "data/reference_extended/edgecase"

reference: "data/references/hg38.fa"
telomere_model: "data/references/M19947.hmm"
chromosome_names: "ucsc"

nhmmer: "tools/hmmer/bin/nhmmer"

datasets:
  - _1_pre_TW
  - _2_flight_TW
  - _3_post_TW
  - _1_pre_HR
  - _2_flight_HR
  - _3_post_HR
